[tool.poetry]
name = "oc_projet12_backend_securise_avec_django_orm"
version = "0.1.0"
description = "Projet 12 du parcours Développeur Python de OpenClassRoom."
authors = ["memphis-tools <rn@github.com>"]
readme = "README.md"
packages = [
  {include = "clients", from = "src"},
  {include = "controllers", from = "src"},
  {include = "models", from = "src"},
  {include = "settings", from = "src"},
  {include = "utils", from = "src"},
  {include = "views", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.5"
rich = "^13.4.2"
requests-oauthlib = "^1.3.1"
sqlalchemy = "^2.0.19"
psycopg = "^3.1.9"
black = "^23.7.0"
pylint = "^2.17.4"
sqlalchemy-utils = "^0.41.1"
pytest = "^7.4.0"
flake8-html = "^0.4.3"
pyjwt = {extras = ["crypto"], version = "^2.7.0"}
pytest-cov = "^4.1.0"
python-dotenv = "^1.0.0"

[tool.poetry.scripts]
launch_application = "clients.console:launch_application"
get_clients = "clients.console:get_clients"
get_collaborators = "clients.console:get_collaborators"
get_contracts = "clients.console:get_contracts"
get_departments = "clients.console:get_departments"
get_events = "clients.console:get_events"
get_locations = "clients.console:get_locations"
get_roles = "clients.console:get_roles"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
